server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
  application:
    name: QUIZ-APP
    version: 1.1
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=Quiz;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123
app:
  cors:
    allowed-origins: http://localhost:3000
